[files]
max_size_kb_anon = 10240                  # 10 MiB per upload for anonymous
max_size_kb_users = 1048576               # 1GiB per upload for registered users
max_storage_per_user = 5242880            # 5GiB max for all files per user
max_storage = 52428800                    # 50GiB max for everything
storage_dir = "/tmp/tempfiles-rs/storage" # save files here
default_expiration_days = 60              # files are deleted after 60 days
delete_old_files = true                   # will delete old files if the used storage would be over max_storage

[accounts]
allow_anon = true          # allow anonymous uploads
allow_registration = false # allow account registration without invite


[service]
secret = "7UznN0NBPegSCetoXvETJJvW9Ewk8iGw9D2ortfy"
rate_limit_window_ms = 300000                       # 5 min
rate_limit_max_uploads = 20                         # 20 uploads per window max
db_sqlite = "/tmp/tempfiles-rs/db.sqlite"           # path to the database
bind = "0.0.0.0:8000"
base_url = "http://localhost:8000"
